### PR TITLE
added comments, fixes #2

### LINKED ISSUE #2: Doesn't preserve double slash for URLs that don't have http/https specified.
If I do `urlJoin('//www.mywebsite.com/', 'whatever')` it will return `/www.mywebsite.com/whatever`. I want to preserve the double slash so that the browser will use whatever transport it can.

### PR DESCRIPTION
**Pull request by rauberdaniel**
this fixes #2

### CODE REVIEW

**Comment by jfromaniello** [comment]
Hi, thanks a lot. Can you add a test to reproduce this issue?

**Comment by rauberdaniel** [comment]
@jfromaniello yes sure, I will take a look at that :)

**Comment by rauberdaniel** [comment]
@jfromaniello Okay so I did a major rewrite now because 6 replace calls were feeling a little much… So I replaced the whole functionality with 3 replace calls.

I think it would be great to also be able to pass options (e.g. `keepTrailingSlash`, like requested in #10) to url-join but I guess that’s currently not so easy because the call arguments are all used for concatenation.

**Comment by jfromaniello** [comment]
This is very well done! Thank you, I published it as `v1.0.0`.

**Comment by rauberdaniel** [comment]
@jfromaniello thank you very much!

**Pull request merged**
