### PR TITLE
Added some new tests for cases that fail.

### PR DESCRIPTION
**Pull request by keskival**
These cases are not correctly processed.

### CODE REVIEW

**Comment by jfromaniello** [comment]
Thanks and sorry for the delay. I published this as `url-join@2.0.3`.

**Comment by jfromaniello** [comment]
Heads up.. I had to rever this PR because it breaks other stuff and usage, oops Sorry!.

Master has the tests you added with `.skip` because I still think is important to solve these

**Comment by keskival** [comment]
Thanks anyway! The problems are because my heuristics assume the first part should contain the protocol part, and detects that with ":". One way to fix is to add a condition of no slashes or colons before the assumed protocol colon.
All this is a bit ambiguous, because what we are doing is basically applying heuristics to fix malformed parameters. One thing we must not do is to modify legal URLs. There should be a larger set of tests to make sure legal inputs are not being modified, but are simply concatenated.

**Comment by keskival** [comment]
@jfromaniello : Fixed the discovered issue here: https://github.com/jfromaniello/url-join/pull/35

**Pull request merged**
