### PR TITLE
Add file protocol support

### PR DESCRIPTION
**Pull request by xtuc**
Support for file protocol.

My use case is on cordova, with URLs like: `file:///android_asset/...`

Published this version at: https://www.npmjs.com/package/@xtuc/url-join

### CODE REVIEW

**Comment by jfromaniello** [comment]
@xtuc thank you very much for doing this!

There is just one small thing that I don't like, the polyfill for `startWith`. I don't like libs that  override global prototypes like Array, String, etc.

I think it will be better to have a func like:

```javascript
function startsWith(str, term) {
  if (typeof str.startsWith !== 'undefined') { return str.startsWith(term); }
  return str.substr(position, searchString.length) === searchString;
}
```

**Comment by xtuc** [comment]
I absolutely agree with you! I made the changes.

**Comment by jfromaniello** [comment]
Thank you very much, since this change the behavior for `file://` I published as a new major version `v2.0.0`.

**Comment by xtuc** [comment]
That's great, thanks.

**Pull request merged**
